name: picy_trade
description: "A online marketplace for buy and sell pictures."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

#=============================================================


dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.8
  in_app_purchase: ^3.2.3
  flutter_svg: ^2.2.1


#=============================================================


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true



  assets:
    - assets/icon/
    - assets/images/
    - assets/product_image_sample/

  fonts:
    - family: awesomeFont
      fonts:
        - asset: assets/font/BBHS.ttf

flutter_native_splash:
  color: "#95fcfb"
  image: assets/icon/app_icon_circle.png
  android_12:
    color: "#95fcfb"
    image: assets/icon/app_icon_circle.png
  web: false